package com.weipai.mapper;

import com.weipai.model.BetlogLot;
import java.util.List;
import java.util.Map;

import org.apache.ibatis.annotations.Param;

public interface BetlogLotMapper {
    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table betlog_lot
     *
     * @mbggenerated
     */
    int deleteByPrimaryKey(Integer id);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table betlog_lot
     *
     * @mbggenerated
     */
    int insert(BetlogLot record);
    
    int minu4insertSelective(Map<String,Object> map);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table betlog_lot
     *
     * @mbggenerated
     */
    int insertSelective(BetlogLot record);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table betlog_lot
     *
     * @mbggenerated
     */
    
    List<BetlogLot> getRecentBetlogLot(Map<String,Object> map);
    
    List<BetlogLot> getRecentBetlogLotWinner(Map<String,Object> map);
    
    List<BetlogLot> selectExistCurUuidBets(Map<String,Object> map);
    
    int openLot(Map<String,Object> map);
    
    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table betlog_lot
     *
     * @mbggenerated
     */
    BetlogLot selectByPrimaryKey(Integer id);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table betlog_lot
     *
     * @mbggenerated
     */

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table betlog_lot
     *
     * @mbggenerated
     */
    int updateByPrimaryKeySelective(BetlogLot record);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table betlog_lot
     *
     * @mbggenerated
     */
    int updateByPrimaryKey(BetlogLot record);
}