package com.weipai.mapper;

import java.util.List;
import java.util.Map;

import com.weipai.model.ExchangeLot;
import com.weipai.model.ExchangeLotExt;

public interface ExchangeLotMapper {
    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table exchange_lot
     *
     * @mbggenerated
     */
    int deleteByPrimaryKey(Integer id);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table exchange_lot
     *
     * @mbggenerated
     */
    int insert(ExchangeLot record);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table exchange_lot
     *
     * @mbggenerated
     */
    int insertSelective(ExchangeLot record);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table exchange_lot
     *
     * @mbggenerated
     */
    ExchangeLot selectByPrimaryKey(Integer id);
    List<ExchangeLotExt> selectByMidTime(Map<String, Object> params);
    int selectCount(Map<String,Object> params);
    
    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table exchange_lot
     *
     * @mbggenerated
     */
    int updateByPrimaryKeySelective(ExchangeLot record);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table exchange_lot
     *
     * @mbggenerated
     */
    int updateByPrimaryKey(ExchangeLot record);
}