package com.weipai.mapper;

import com.weipai.model.Generallog;

public interface GenerallogMapper {
    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table generallog
     *
     * @mbggenerated
     */
    int deleteByPrimaryKey(Integer id);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table generallog
     *
     * @mbggenerated
     */
    int insert(Generallog record);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table generallog
     *
     * @mbggenerated
     */
    int insertSelective(Generallog record);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table generallog
     *
     * @mbggenerated
     */
    Generallog selectByPrimaryKey(Integer id);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table generallog
     *
     * @mbggenerated
     */
    int updateByPrimaryKeySelective(Generallog record);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table generallog
     *
     * @mbggenerated
     */
    int updateByPrimaryKey(Generallog record);
}