package com.weipai.model;

import java.util.Date;

public class BetlogLot {

	/**
	 * This field was generated by MyBatis Generator. This field corresponds to the database column betlog_lot.id
	 * @mbggenerated
	 */
	private Integer id;
	/**
	 * This field was generated by MyBatis Generator. This field corresponds to the database column betlog_lot.managerId
	 * @mbggenerated
	 */
	private Integer managerid;
	/**
	 * This field was generated by MyBatis Generator. This field corresponds to the database column betlog_lot.uuid
	 * @mbggenerated
	 */
	private Integer uuid;
	/**
	 * This field was generated by MyBatis Generator. This field corresponds to the database column betlog_lot.serialNum
	 * @mbggenerated
	 */
	private Integer serialnum;
	/**
	 * This field was generated by MyBatis Generator. This field corresponds to the database column betlog_lot.lotId
	 * @mbggenerated
	 */
	private Integer lotid;
	/**
	 * This field was generated by MyBatis Generator. This field corresponds to the database column betlog_lot.betType
	 * @mbggenerated
	 */
	private Integer bettype;
	/**
	 * This field was generated by MyBatis Generator. This field corresponds to the database column betlog_lot.betMount
	 * @mbggenerated
	 */
	private Integer betmount;
	/**
	 * This field was generated by MyBatis Generator. This field corresponds to the database column betlog_lot.betResult
	 * @mbggenerated
	 */
	private Integer betresult;
	/**
	 * This field was generated by MyBatis Generator. This field corresponds to the database column betlog_lot.createTime
	 * @mbggenerated
	 */
	private Date createtime;
	/**
	 * This field was generated by MyBatis Generator. This field corresponds to the database column betlog_lot.lotResult
	 * @mbggenerated
	 */
	private String lotresult;
	/**
	 * This field was generated by MyBatis Generator. This field corresponds to the database column betlog_lot.facevalue
	 * @mbggenerated
	 */
	private String facevalue;
	/**
	 * This field was generated by MyBatis Generator. This field corresponds to the database column betlog_lot.cardcount
	 * @mbggenerated
	 */
	private String cardcount;

	/**
	 * This method was generated by MyBatis Generator. This method returns the value of the database column betlog_lot.id
	 * @return  the value of betlog_lot.id
	 * @mbggenerated
	 */
	public Integer getId() {
		return id;
	}

	/**
	 * This method was generated by MyBatis Generator. This method sets the value of the database column betlog_lot.id
	 * @param id  the value for betlog_lot.id
	 * @mbggenerated
	 */
	public void setId(Integer id) {
		this.id = id;
	}

	/**
	 * This method was generated by MyBatis Generator. This method returns the value of the database column betlog_lot.managerId
	 * @return  the value of betlog_lot.managerId
	 * @mbggenerated
	 */
	public Integer getManagerid() {
		return managerid;
	}

	/**
	 * This method was generated by MyBatis Generator. This method sets the value of the database column betlog_lot.managerId
	 * @param managerid  the value for betlog_lot.managerId
	 * @mbggenerated
	 */
	public void setManagerid(Integer managerid) {
		this.managerid = managerid;
	}

	/**
	 * This method was generated by MyBatis Generator. This method returns the value of the database column betlog_lot.uuid
	 * @return  the value of betlog_lot.uuid
	 * @mbggenerated
	 */
	public Integer getUuid() {
		return uuid;
	}

	/**
	 * This method was generated by MyBatis Generator. This method sets the value of the database column betlog_lot.uuid
	 * @param uuid  the value for betlog_lot.uuid
	 * @mbggenerated
	 */
	public void setUuid(Integer uuid) {
		this.uuid = uuid;
	}

	/**
	 * This method was generated by MyBatis Generator. This method returns the value of the database column betlog_lot.serialNum
	 * @return  the value of betlog_lot.serialNum
	 * @mbggenerated
	 */
	public Integer getSerialnum() {
		return serialnum;
	}

	/**
	 * This method was generated by MyBatis Generator. This method sets the value of the database column betlog_lot.serialNum
	 * @param serialnum  the value for betlog_lot.serialNum
	 * @mbggenerated
	 */
	public void setSerialnum(Integer serialnum) {
		this.serialnum = serialnum;
	}

	/**
	 * This method was generated by MyBatis Generator. This method returns the value of the database column betlog_lot.lotId
	 * @return  the value of betlog_lot.lotId
	 * @mbggenerated
	 */
	public Integer getLotid() {
		return lotid;
	}

	/**
	 * This method was generated by MyBatis Generator. This method sets the value of the database column betlog_lot.lotId
	 * @param lotid  the value for betlog_lot.lotId
	 * @mbggenerated
	 */
	public void setLotid(Integer lotid) {
		this.lotid = lotid;
	}

	/**
	 * This method was generated by MyBatis Generator. This method returns the value of the database column betlog_lot.betType
	 * @return  the value of betlog_lot.betType
	 * @mbggenerated
	 */
	public Integer getBettype() {
		return bettype;
	}

	/**
	 * This method was generated by MyBatis Generator. This method sets the value of the database column betlog_lot.betType
	 * @param bettype  the value for betlog_lot.betType
	 * @mbggenerated
	 */
	public void setBettype(Integer bettype) {
		this.bettype = bettype;
	}

	/**
	 * This method was generated by MyBatis Generator. This method returns the value of the database column betlog_lot.betMount
	 * @return  the value of betlog_lot.betMount
	 * @mbggenerated
	 */
	public Integer getBetmount() {
		return betmount;
	}

	/**
	 * This method was generated by MyBatis Generator. This method sets the value of the database column betlog_lot.betMount
	 * @param betmount  the value for betlog_lot.betMount
	 * @mbggenerated
	 */
	public void setBetmount(Integer betmount) {
		this.betmount = betmount;
	}

	/**
	 * This method was generated by MyBatis Generator. This method returns the value of the database column betlog_lot.betResult
	 * @return  the value of betlog_lot.betResult
	 * @mbggenerated
	 */
	public Integer getBetresult() {
		return betresult;
	}

	/**
	 * This method was generated by MyBatis Generator. This method sets the value of the database column betlog_lot.betResult
	 * @param betresult  the value for betlog_lot.betResult
	 * @mbggenerated
	 */
	public void setBetresult(Integer betresult) {
		this.betresult = betresult;
	}

	/**
	 * This method was generated by MyBatis Generator. This method returns the value of the database column betlog_lot.createTime
	 * @return  the value of betlog_lot.createTime
	 * @mbggenerated
	 */
	public Date getCreatetime() {
		return createtime;
	}

	/**
	 * This method was generated by MyBatis Generator. This method sets the value of the database column betlog_lot.createTime
	 * @param createtime  the value for betlog_lot.createTime
	 * @mbggenerated
	 */
	public void setCreatetime(Date createtime) {
		this.createtime = createtime;
	}

	/**
	 * This method was generated by MyBatis Generator. This method returns the value of the database column betlog_lot.lotResult
	 * @return  the value of betlog_lot.lotResult
	 * @mbggenerated
	 */
	public String getLotresult() {
		return lotresult;
	}

	/**
	 * This method was generated by MyBatis Generator. This method sets the value of the database column betlog_lot.lotResult
	 * @param lotresult  the value for betlog_lot.lotResult
	 * @mbggenerated
	 */
	public void setLotresult(String lotresult) {
		this.lotresult = lotresult == null ? null : lotresult.trim();
	}

	/**
	 * This method was generated by MyBatis Generator. This method returns the value of the database column betlog_lot.facevalue
	 * @return  the value of betlog_lot.facevalue
	 * @mbggenerated
	 */
	public String getFacevalue() {
		return facevalue;
	}

	/**
	 * This method was generated by MyBatis Generator. This method sets the value of the database column betlog_lot.facevalue
	 * @param facevalue  the value for betlog_lot.facevalue
	 * @mbggenerated
	 */
	public void setFacevalue(String facevalue) {
		this.facevalue = facevalue == null ? null : facevalue.trim();
	}

	/**
	 * This method was generated by MyBatis Generator. This method returns the value of the database column betlog_lot.cardcount
	 * @return  the value of betlog_lot.cardcount
	 * @mbggenerated
	 */
	public String getCardcount() {
		return cardcount;
	}

	/**
	 * This method was generated by MyBatis Generator. This method sets the value of the database column betlog_lot.cardcount
	 * @param cardcount  the value for betlog_lot.cardcount
	 * @mbggenerated
	 */
	public void setCardcount(String cardcount) {
		this.cardcount = cardcount == null ? null : cardcount.trim();
	}
}