package com.weipai.model;

public class Bonus {
    /**
     *
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column bonus.id
     *
     * @mbggenerated
     */
    private Integer id;

    /**
     *
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column bonus.paylogId
     *
     * @mbggenerated
     */
    private Integer paylogid;

    /**
     *
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column bonus.managerId
     *
     * @mbggenerated
     */
    private Integer managerid;

    /**
     *
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column bonus.money
     *
     * @mbggenerated
     */
    private Double money;

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column bonus.id
     *
     * @return the value of bonus.id
     *
     * @mbggenerated
     */
    public Integer getId() {
        return id;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column bonus.id
     *
     * @param id the value for bonus.id
     *
     * @mbggenerated
     */
    public void setId(Integer id) {
        this.id = id;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column bonus.paylogId
     *
     * @return the value of bonus.paylogId
     *
     * @mbggenerated
     */
    public Integer getPaylogid() {
        return paylogid;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column bonus.paylogId
     *
     * @param paylogid the value for bonus.paylogId
     *
     * @mbggenerated
     */
    public void setPaylogid(Integer paylogid) {
        this.paylogid = paylogid;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column bonus.managerId
     *
     * @return the value of bonus.managerId
     *
     * @mbggenerated
     */
    public Integer getManagerid() {
        return managerid;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column bonus.managerId
     *
     * @param managerid the value for bonus.managerId
     *
     * @mbggenerated
     */
    public void setManagerid(Integer managerid) {
        this.managerid = managerid;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column bonus.money
     *
     * @return the value of bonus.money
     *
     * @mbggenerated
     */
    public Double getMoney() {
        return money;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column bonus.money
     *
     * @param money the value for bonus.money
     *
     * @mbggenerated
     */
    public void setMoney(Double money) {
        this.money = money;
    }
}