package com.weipai.model;

import java.util.Date;

public class Generallog {
    /**
     *
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column generallog.id
     *
     * @mbggenerated
     */
    private Integer id;

    /**
     *
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column generallog.type
     *
     * @mbggenerated
     */
    private Integer type;

    /**
     *
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column generallog.content
     *
     * @mbggenerated
     */
    private String content;

    /**
     *
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column generallog.createTime
     *
     * @mbggenerated
     */
    private Date createtime;

    /**
     *
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column generallog.managerId
     *
     * @mbggenerated
     */
    private Integer managerid;

    /**
     *
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column generallog.uuid
     *
     * @mbggenerated
     */
    private Integer uuid;

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column generallog.id
     *
     * @return the value of generallog.id
     *
     * @mbggenerated
     */
    public Integer getId() {
        return id;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column generallog.id
     *
     * @param id the value for generallog.id
     *
     * @mbggenerated
     */
    public void setId(Integer id) {
        this.id = id;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column generallog.type
     *
     * @return the value of generallog.type
     *
     * @mbggenerated
     */
    public Integer getType() {
        return type;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column generallog.type
     *
     * @param type the value for generallog.type
     *
     * @mbggenerated
     */
    public void setType(Integer type) {
        this.type = type;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column generallog.content
     *
     * @return the value of generallog.content
     *
     * @mbggenerated
     */
    public String getContent() {
        return content;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column generallog.content
     *
     * @param content the value for generallog.content
     *
     * @mbggenerated
     */
    public void setContent(String content) {
        this.content = content == null ? null : content.trim();
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column generallog.createTime
     *
     * @return the value of generallog.createTime
     *
     * @mbggenerated
     */
    public Date getCreatetime() {
        return createtime;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column generallog.createTime
     *
     * @param createtime the value for generallog.createTime
     *
     * @mbggenerated
     */
    public void setCreatetime(Date createtime) {
        this.createtime = createtime;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column generallog.managerId
     *
     * @return the value of generallog.managerId
     *
     * @mbggenerated
     */
    public Integer getManagerid() {
        return managerid;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column generallog.managerId
     *
     * @param managerid the value for generallog.managerId
     *
     * @mbggenerated
     */
    public void setManagerid(Integer managerid) {
        this.managerid = managerid;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column generallog.uuid
     *
     * @return the value of generallog.uuid
     *
     * @mbggenerated
     */
    public Integer getUuid() {
        return uuid;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column generallog.uuid
     *
     * @param uuid the value for generallog.uuid
     *
     * @mbggenerated
     */
    public void setUuid(Integer uuid) {
        this.uuid = uuid;
    }
}