package com.weipai.model;

import java.util.Date;

public class PaylogLot {
    /**
     *
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column paylog_lot.id
     *
     * @mbggenerated
     */
    private Integer id;

    /**
     *
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column paylog_lot.managerId
     *
     * @mbggenerated
     */
    private Integer managerid;

    /**
     *
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column paylog_lot.uuid
     *
     * @mbggenerated
     */
    private Integer uuid;

    /**
     *
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column paylog_lot.money
     *
     * @mbggenerated
     */
    private Double money;

    /**
     *
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column paylog_lot.payCount
     *
     * @mbggenerated
     */
    private Integer paycount;

    /**
     *
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column paylog_lot.payTime
     *
     * @mbggenerated
     */
    private Date paytime;

    /**
     *
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column paylog_lot.payType
     *
     * @mbggenerated
     */
    private Integer paytype;

    /**
     *
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column paylog_lot.status
     *
     * @mbggenerated
     */
    private Integer status;

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column paylog_lot.id
     *
     * @return the value of paylog_lot.id
     *
     * @mbggenerated
     */
    public Integer getId() {
        return id;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column paylog_lot.id
     *
     * @param id the value for paylog_lot.id
     *
     * @mbggenerated
     */
    public void setId(Integer id) {
        this.id = id;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column paylog_lot.managerId
     *
     * @return the value of paylog_lot.managerId
     *
     * @mbggenerated
     */
    public Integer getManagerid() {
        return managerid;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column paylog_lot.managerId
     *
     * @param managerid the value for paylog_lot.managerId
     *
     * @mbggenerated
     */
    public void setManagerid(Integer managerid) {
        this.managerid = managerid;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column paylog_lot.uuid
     *
     * @return the value of paylog_lot.uuid
     *
     * @mbggenerated
     */
    public Integer getUuid() {
        return uuid;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column paylog_lot.uuid
     *
     * @param uuid the value for paylog_lot.uuid
     *
     * @mbggenerated
     */
    public void setUuid(Integer uuid) {
        this.uuid = uuid;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column paylog_lot.money
     *
     * @return the value of paylog_lot.money
     *
     * @mbggenerated
     */
    public Double getMoney() {
        return money;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column paylog_lot.money
     *
     * @param money the value for paylog_lot.money
     *
     * @mbggenerated
     */
    public void setMoney(Double money) {
        this.money = money;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column paylog_lot.payCount
     *
     * @return the value of paylog_lot.payCount
     *
     * @mbggenerated
     */
    public Integer getPaycount() {
        return paycount;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column paylog_lot.payCount
     *
     * @param paycount the value for paylog_lot.payCount
     *
     * @mbggenerated
     */
    public void setPaycount(Integer paycount) {
        this.paycount = paycount;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column paylog_lot.payTime
     *
     * @return the value of paylog_lot.payTime
     *
     * @mbggenerated
     */
    public Date getPaytime() {
        return paytime;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column paylog_lot.payTime
     *
     * @param paytime the value for paylog_lot.payTime
     *
     * @mbggenerated
     */
    public void setPaytime(Date paytime) {
        this.paytime = paytime;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column paylog_lot.payType
     *
     * @return the value of paylog_lot.payType
     *
     * @mbggenerated
     */
    public Integer getPaytype() {
        return paytype;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column paylog_lot.payType
     *
     * @param paytype the value for paylog_lot.payType
     *
     * @mbggenerated
     */
    public void setPaytype(Integer paytype) {
        this.paytype = paytype;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column paylog_lot.status
     *
     * @return the value of paylog_lot.status
     *
     * @mbggenerated
     */
    public Integer getStatus() {
        return status;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column paylog_lot.status
     *
     * @param status the value for paylog_lot.status
     *
     * @mbggenerated
     */
    public void setStatus(Integer status) {
        this.status = status;
    }
}