package com.weipai.model;

import java.util.Date;

public class PaylogExt {

	private Integer id;
	
	private String dateString;

	private Integer managerid;

	private Integer uuid;

	private Double money;

	private Integer paycount;

	private Date paytime;

	private Integer paytype;

	private Integer status;
	
	private Integer invitecode;
	private Integer powerid;
	
	private Integer invitecode1;
	private Integer powerid1;
	
	
	private Integer invitecode2;
	private Integer powerid2;
	
	
	private Integer invitecode3;
	private Integer powerid3;
    private String nickName;
    
    private Double bonus;
    
	public Double getBonus() {
		return bonus;
	}

	public void setBonus(Double bonus) {
		this.bonus = bonus;
	}

	public String getNickName() {
		return nickName;
	}

	public void setNickName(String nickName) {
		this.nickName = nickName;
	}

	/**
	 * This method was generated by MyBatis Generator. This method returns the value of the database column paylog.id
	 * @return  the value of paylog.id
	 * @mbggenerated
	 */
	public Integer getId() {
		return id;
	}

	/**
	 * This method was generated by MyBatis Generator. This method sets the value of the database column paylog.id
	 * @param id  the value for paylog.id
	 * @mbggenerated
	 */
	public void setId(Integer id) {
		this.id = id;
	}

	/**
	 * This method was generated by MyBatis Generator. This method returns the value of the database column paylog.managerId
	 * @return  the value of paylog.managerId
	 * @mbggenerated
	 */
	public Integer getManagerid() {
		return managerid;
	}

	/**
	 * This method was generated by MyBatis Generator. This method sets the value of the database column paylog.managerId
	 * @param managerid  the value for paylog.managerId
	 * @mbggenerated
	 */
	public void setManagerid(Integer managerid) {
		this.managerid = managerid;
	}

	/**
	 * This method was generated by MyBatis Generator. This method returns the value of the database column paylog.uuid
	 * @return  the value of paylog.uuid
	 * @mbggenerated
	 */
	public Integer getUuid() {
		return uuid;
	}

	/**
	 * This method was generated by MyBatis Generator. This method sets the value of the database column paylog.uuid
	 * @param uuid  the value for paylog.uuid
	 * @mbggenerated
	 */
	public void setUuid(Integer uuid) {
		this.uuid = uuid;
	}

	/**
	 * This method was generated by MyBatis Generator. This method returns the value of the database column paylog.money
	 * @return  the value of paylog.money
	 * @mbggenerated
	 */
	public Double getMoney() {
		return money;
	}

	/**
	 * This method was generated by MyBatis Generator. This method sets the value of the database column paylog.money
	 * @param money  the value for paylog.money
	 * @mbggenerated
	 */
	public void setMoney(Double money) {
		this.money = money;
	}

	/**
	 * This method was generated by MyBatis Generator. This method returns the value of the database column paylog.payCount
	 * @return  the value of paylog.payCount
	 * @mbggenerated
	 */
	public Integer getPaycount() {
		return paycount;
	}

	/**
	 * This method was generated by MyBatis Generator. This method sets the value of the database column paylog.payCount
	 * @param paycount  the value for paylog.payCount
	 * @mbggenerated
	 */
	public void setPaycount(Integer paycount) {
		this.paycount = paycount;
	}

	/**
	 * This method was generated by MyBatis Generator. This method returns the value of the database column paylog.payTime
	 * @return  the value of paylog.payTime
	 * @mbggenerated
	 */
	public Date getPaytime() {
		return paytime;
	}

	/**
	 * This method was generated by MyBatis Generator. This method sets the value of the database column paylog.payTime
	 * @param paytime  the value for paylog.payTime
	 * @mbggenerated
	 */
	public void setPaytime(Date paytime) {
		this.paytime = paytime;
	}

	/**
	 * This method was generated by MyBatis Generator. This method returns the value of the database column paylog.payType
	 * @return  the value of paylog.payType
	 * @mbggenerated
	 */
	public Integer getPaytype() {
		return paytype;
	}

	/**
	 * This method was generated by MyBatis Generator. This method sets the value of the database column paylog.payType
	 * @param paytype  the value for paylog.payType
	 * @mbggenerated
	 */
	public void setPaytype(Integer paytype) {
		this.paytype = paytype;
	}

	/**
	 * This method was generated by MyBatis Generator. This method returns the value of the database column paylog.status
	 * @return  the value of paylog.status
	 * @mbggenerated
	 */
	public Integer getStatus() {
		return status;
	}

	/**
	 * This method was generated by MyBatis Generator. This method sets the value of the database column paylog.status
	 * @param status  the value for paylog.status
	 * @mbggenerated
	 */
	public void setStatus(Integer status) {
		this.status = status;
	}

	public String getDateString() {
		return dateString;
	}

	public void setDateString(String dateString) {
		this.dateString = dateString;
	}

	public Integer getInvitecode() {
		return invitecode;
	}

	public void setInvitecode(Integer invitecode) {
		this.invitecode = invitecode;
	}

	public Integer getPowerid() {
		return powerid;
	}

	public void setPowerid(Integer powerid) {
		this.powerid = powerid;
	}

	public Integer getInvitecode1() {
		return invitecode1;
	}

	public void setInvitecode1(Integer invitecode1) {
		this.invitecode1 = invitecode1;
	}

	public Integer getPowerid1() {
		return powerid1;
	}

	public void setPowerid1(Integer powerid1) {
		this.powerid1 = powerid1;
	}

	public Integer getInvitecode2() {
		return invitecode2;
	}

	public void setInvitecode2(Integer invitecode2) {
		this.invitecode2 = invitecode2;
	}

	public Integer getPowerid2() {
		return powerid2;
	}

	public void setPowerid2(Integer powerid2) {
		this.powerid2 = powerid2;
	}

	public Integer getInvitecode3() {
		return invitecode3;
	}

	public void setInvitecode3(Integer invitecode3) {
		this.invitecode3 = invitecode3;
	}

	public Integer getPowerid3() {
		return powerid3;
	}

	public void setPowerid3(Integer powerid3) {
		this.powerid3 = powerid3;
	}
	
	
	
	
}