package com.weipai.model;

import java.util.Date;

public class ResultLot {
    /**
     *
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column result_lot.id
     *
     * @mbggenerated
     */
    private Integer id;

    /**
     *
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column result_lot.serialNum
     *
     * @mbggenerated
     */
    private Integer serialnum;

    /**
     *
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column result_lot.openTime
     *
     * @mbggenerated
     */
    private Date opentime;

    /**
     *
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column result_lot.lotId
     *
     * @mbggenerated
     */
    private Integer lotid;

    /**
     *
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column result_lot.result
     *
     * @mbggenerated
     */
    private String result;

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column result_lot.id
     *
     * @return the value of result_lot.id
     *
     * @mbggenerated
     */
    public Integer getId() {
        return id;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column result_lot.id
     *
     * @param id the value for result_lot.id
     *
     * @mbggenerated
     */
    public void setId(Integer id) {
        this.id = id;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column result_lot.serialNum
     *
     * @return the value of result_lot.serialNum
     *
     * @mbggenerated
     */
    public Integer getSerialnum() {
        return serialnum;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column result_lot.serialNum
     *
     * @param serialnum the value for result_lot.serialNum
     *
     * @mbggenerated
     */
    public void setSerialnum(Integer serialnum) {
        this.serialnum = serialnum;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column result_lot.openTime
     *
     * @return the value of result_lot.openTime
     *
     * @mbggenerated
     */
    public Date getOpentime() {
        return opentime;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column result_lot.openTime
     *
     * @param opentime the value for result_lot.openTime
     *
     * @mbggenerated
     */
    public void setOpentime(Date opentime) {
        this.opentime = opentime;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column result_lot.lotId
     *
     * @return the value of result_lot.lotId
     *
     * @mbggenerated
     */
    public Integer getLotid() {
        return lotid;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column result_lot.lotId
     *
     * @param lotid the value for result_lot.lotId
     *
     * @mbggenerated
     */
    public void setLotid(Integer lotid) {
        this.lotid = lotid;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column result_lot.result
     *
     * @return the value of result_lot.result
     *
     * @mbggenerated
     */
    public String getResult() {
        return result;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column result_lot.result
     *
     * @param result the value for result_lot.result
     *
     * @mbggenerated
     */
    public void setResult(String result) {
        this.result = result == null ? null : result.trim();
    }
}