package com.weipai.model;

import java.util.Date;

public class Roomcardlog {
    /**
     *
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column roomcardlog.id
     *
     * @mbggenerated
     */
    private Integer id;

    /**
     *
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column roomcardlog.managerId
     *
     * @mbggenerated
     */
    private Integer managerid;

    /**
     *
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column roomcardlog.accountId
     *
     * @mbggenerated
     */
    private Integer accountid;

    /**
     *
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column roomcardlog.roomCard
     *
     * @mbggenerated
     */
    private Integer roomcard;

    /**
     *
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column roomcardlog.createtime
     *
     * @mbggenerated
     */
    private Date createtime;

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column roomcardlog.id
     *
     * @return the value of roomcardlog.id
     *
     * @mbggenerated
     */
    public Integer getId() {
        return id;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column roomcardlog.id
     *
     * @param id the value for roomcardlog.id
     *
     * @mbggenerated
     */
    public void setId(Integer id) {
        this.id = id;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column roomcardlog.managerId
     *
     * @return the value of roomcardlog.managerId
     *
     * @mbggenerated
     */
    public Integer getManagerid() {
        return managerid;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column roomcardlog.managerId
     *
     * @param managerid the value for roomcardlog.managerId
     *
     * @mbggenerated
     */
    public void setManagerid(Integer managerid) {
        this.managerid = managerid;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column roomcardlog.accountId
     *
     * @return the value of roomcardlog.accountId
     *
     * @mbggenerated
     */
    public Integer getAccountid() {
        return accountid;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column roomcardlog.accountId
     *
     * @param accountid the value for roomcardlog.accountId
     *
     * @mbggenerated
     */
    public void setAccountid(Integer accountid) {
        this.accountid = accountid;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column roomcardlog.roomCard
     *
     * @return the value of roomcardlog.roomCard
     *
     * @mbggenerated
     */
    public Integer getRoomcard() {
        return roomcard;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column roomcardlog.roomCard
     *
     * @param roomcard the value for roomcardlog.roomCard
     *
     * @mbggenerated
     */
    public void setRoomcard(Integer roomcard) {
        this.roomcard = roomcard;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column roomcardlog.createtime
     *
     * @return the value of roomcardlog.createtime
     *
     * @mbggenerated
     */
    public Date getCreatetime() {
        return createtime;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column roomcardlog.createtime
     *
     * @param createtime the value for roomcardlog.createtime
     *
     * @mbggenerated
     */
    public void setCreatetime(Date createtime) {
        this.createtime = createtime;
    }
}